name: skip-ui
on:
  push:
    branches: [ main ]
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: Ceylo/actions/.github/workflows/skip-framework.yml@test/skip-linux-override
    with:
      runs-on: "['macos-26', 'ubuntu-24.04']"
      env: |
        SKIP_LINUX_OVERRIDE_RUN=__RUN__
